{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "k8s-helm.fullname" . }}
  labels:
    {{- include "k8s-helm.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.secrets.spec | nindent 2 }}
  

{{- end }}