name: Update Helm Chart Values

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
      environment:
        description: 'Environment (e.g., dev, stag, prod)'
        required: true
      project_name:
        description: 'Name of the project'
        required: true

jobs:
  update-helm-values:
    runs-on: ubuntu-latest
    name: Update Values in Helm Chart

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: dhenob/helm-charts
        ref: main

    - name: Set up Environment
      run: |
        echo "PROJECT_NAME=${{ github.event.inputs.project_name }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

    - name: Debug Output
      run: |
        echo "Image Tag: $IMAGE_TAG"
        echo "Project Name: $PROJECT_NAME"
        echo "Environment: $ENVIRONMENT"

    - name: Update Helm Chart Values
      run: |
        FILE_TO_UPDATE="values-${ENVIRONMENT}.yaml"
        sed -i "s/tag: .*/tag: $IMAGE_TAG/g" $FILE_TO_UPDATE
        echo "UPDATED_VALUES_FILE=$FILE_TO_UPDATE" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}/${{ github.event.inputs.project_name }}

    - name: Commit and Push Updated Values File
      run: |
        UPDATED_VALUES_FILE="$PROJECT_NAME/$UPDATED_VALUES_FILE"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add $UPDATED_VALUES_FILE
        git status
        git diff --cached --exit-code || git commit -m "Update image tag to $IMAGE_TAG for $PROJECT_NAME [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
